const LOGGED_IN = "LOGGED_IN";
const PERMISSION = "PERMISSION";
const PHONENUMBER = "PHONENUMBER";

const Keys = {
    LOGGED_IN:LOGGED_IN,
    PERMISSION:PERMISSION,
    PHONENUMBER:PHONENUMBER
}
export default Keys;